/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayoutAside: typeof import('./src/components/layout/layout-aside.vue')['default']
    LayoutFooter: typeof import('./src/components/layout/layout-footer.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/layout-header.vue')['default']
    LayoutNav: typeof import('./src/components/layout/layout-nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
